#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > kidotest.cpp
#include <common/Timer.hpp>

using namespace kido::common
int main()
{
   Timer timer1("Timer1");
   timer1.start();
   timer1.stop();
   return 0;
}
EOF

g++ -o kidotest kidotest.cpp `pkg-config --cflags --libs kido`
echo "build: OK"
[ -x kidotest ]
./kidotest
echo "run: OK"
