#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > darttest.cpp
#include <dart/common/Timer.hpp>

using namespace dart::common;
int main()
{
   Timer timer1("Timer1");
   timer1.start();
   timer1.stop();
   return 0;
}
EOF

g++ -o darttest darttest.cpp `pkg-config --cflags --libs dart`
echo "build: OK"
[ -x darttest ]
./darttest
echo "run: OK"

# 2. CMAKE
cat <<EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.5)

project(darttest VERSION 1.0.0)

find_package(DART REQUIRED)
add_executable(darttest darttest.cpp)
target_include_directories(darttest PRIVATE \${DART_INCLUDE_DIRS})
target_link_libraries(darttest \${DART_LIBRARIES})
EOF

cmake .
echo "configure cmake: OK"
make
echo "build cmake:OK"
[ -x darttest ]
./darttest
echo "run: OK"
